### ISSUE TITLE
Home Assistant and Ulanzi communication speed 

### ISSUE THREAD

**Issue by aptonline** [lubeda/EsphoMaTrix#38]
On testing the sample Ulanzi .yaml file I noticed the speed of communication between Home Assistant and Ulanzi to be quite slow. There was a number of seconds between changes.

Appreciate this is still in early stages of development but just wanted to flag 😀.

**Comment by lubeda** [comment]
The communication between home assistant and the display is asynchronous! 
There is a queue on the display that shows all screens after another, as they came in. See diagram in the README.md. 

If you like to force a screen e.g. "door bell rings" you have to send the screen and  [force](https://github.com/lubeda/EsphoMaTrix#force-screen) it. Even that may take some seconds to show up the screen! Force moves the pointer of the next screen to display to the forced screen. !?! 

This is by design!

**Comment by aptonline** [comment]
That’s makes sense now. I was expecting an update as soon as the service was triggered, similar to PixelIt. Thanks for the clarification.
