### ISSUE TITLE
screen brightness

### ISSUE THREAD

**Issue by jrspowers** [lubeda/EsphoMaTrix#55]
hello is it possible to set the startup screen brightness to your own set brightness ? so that it doesn't have to be done every time?

**Comment by pplucky** [comment]
Have you tried this?

```
esphome:
  ....
  on_boot:
    priority: -100
    # ...
    then:
      - lambda: !lambda |-
          id(rgb8x32)->set_brightness(YOURVALUE);
```

I think this should force the brightness to be set to YOURVALUE on esp boot (similar to [show_all_icons example in documentation](https://github.com/lubeda/EsphoMaTrix#show-all-icons-on-your-matrix)).

**Comment by jrspowers** [comment]
thank you I will try that later thank you 😊

**Comment by pplucky** [comment]
> thank @pplucky you this work top & I have another question after restart my screen is always off on my esphomatrix screen can't find where this setting is on my wall ulanzi isn't this the case?

You mean when you restart/boot the esp32, right? 

I only restart mine when I flash it, otherwise I just turn the display off and on with the [corresponding service or switch](https://github.com/lubeda/EsphoMaTrix#services).

Still then, when I restart the esp32, it feels like it doesn't always behave the same way, but it also happens to me some times (not all the time).

What I've seen also - not sure if that's your case, when I'm playing with esphome light effects, if the effect ends up in full black and I don't finish the effect (with effect 'None') or turn off the light, matrix stays all black and doesn't show anything EsphoMaTrix-related (clock or screens).

**Comment by jrspowers** [comment]
yes I mean so if you have updated the config via esphome this sava and install wireless then it restarts anyway & then the screen is black I don't understand why?

**Comment by pplucky** [comment]
You can always try:

esphome:
  ....
  on_boot:
    priority: -100
    # ...
    then:
      - lambda: !lambda |-
          id(rgb8x32)->set_display_on();

But this would only be a workaround anyway. 

Not sure if someone else can try to help a bit more on this (for me), non-consistent behavior..

**Comment by jrspowers** [comment]
thank you very much for helping me this work only at perfect !
